# Generated by Django 4.2.4 on 2023-09-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=1000)),
                ('artist', models.CharField(max_length=1000)),
                ('album_name', models.CharField(max_length=1000)),
                ('album_photo', models.TextField(max_length=1000)),
                ('lyrics', models.TextField(max_length=10000)),
                ('comment', models.TextField(max_length=10000)),
                ('song_play', models.CharField(max_length=1000)),
                ('artist_photo', models.TextField(max_length=1000)),
                ('artist_intro', models.TextField(max_length=10000)),
            ],
        ),
    ]
